services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multilingual-rag-api
    ports:
      - "8000:8000"
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ./cache:/app/cache
    restart: unless-stopped
    networks:
      - rag-network

  rag-gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    container_name: multilingual-rag-gui
    ports:
      - "8503:8501"
    depends_on:
      - rag-api
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 